
# Plantilla de configuración del SERVIDOR (ajusta rutas/puertos según tu entorno)
SSL_CERTIFICATE_ROUTE=demo_tcp.p12
SSL_PASSWORD=123456
SERVER_PORT=8443
PATH_ENFERMEDADES=../../enfermedades
PATH_LOGS=./data/logs/auditoria.log
PATH_EXCEL=./data/pacientes.xlsx
PATH_CSV=./data/pacientes.csv
PATH_FASTA_STORAGE=./data/fasta_recibidos
HASH_ALGO=SHA-256
CSV_SEPARATOR=,
